name: Renovate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate
    steps:
    - run: renovate --reviewers-from-code-owners=true ${{ github.repository }}
      env:
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      shell: bash
