name: Renovate-32.34.1

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write
  security-events: read
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:32.34.1
    steps:
    - run: renovate --reviewers-from-code-owners=true ${{ github.repository }}
      env:
        RENOVATE_HOST_RULES: "[{ \"matchHost\": \"github.com\", \"username\": \"mikhailadvani\", \"password\": \"${{ secrets.RENOVATE_TOKEN }}\"}]"
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        LOG_LEVEL: debug
      shell: bash
